### ISSUE TITLE
No Cast Devices Found

### ISSUE THREAD

**Issue by xmbwd** [muammar/mkchromecast#12]
I installed on Ubuntu 16.04 using the mkchromecast .deb and the python-pychromecast .deb.  Mkchromecast appears to work in all respects except that it cannot find my chromecast device:  No cast device found.  

The Ubuntu computer is on the same network (tried with both ethernet and wifi and both) as the Chromecast.  And the chromecast device (chromecast audio) shows up on my phone.  

Any idea what is going wrong here?

**Comment by muammar** [comment]
It happened to me some times, and rebooting my router and chromecast audio helped sometimes.

**Comment by xmbwd** [comment]
I rebooted both.  No luck.  Other ideas?  If it helps, [pulseaudio-dlna](https://github.com/masmu/pulseaudio-dlna) does not find the chromecast on Ubuntu either.  But the phone does, both via Google Cast and via the AirAudio app.

**Comment by muammar** [comment]
That's estrange. Can you cast from your ubuntu's google chrome to your google cast audio?.

**Comment by xmbwd** [comment]
Yep, weird right.  I **can** cast from my Ubuntu 16.04 computer's Google Chrome app to the chromecast audio.

**Comment by muammar** [comment]
Yes, I don't understand why both pulseaudio-dlna and mkchromecast are not casting to your chromecast audio!.

**Comment by muammar** [comment]
@xmbwd I was thinking about your problem. I read this in the support from Chromecast Help:

> **Some issues can be caused by router or network settings**
> Sometimes Chrome discovers a device on the network, but cannot establish a connection to it. These errors are usually caused by router or networking settings. Please ensure that AP isolation is disabled on your router, and that any firewall features on your router that might block incoming connections to your Google Cast speakers are not enabled.

You could verify that ubuntu's firewall is disabled with`ufw status`.

**Comment by xmbwd** [comment]
Thanks, I saw that too.  The firewall is inactive.  

I used a fourth computer I had with Ubuntu on it, and it **was** able to find the Chromecast.  So it is clearly a conflicting application or a setting I screwed up in the other 3 Ubuntu instances.  

I did notice that the instance that worked did not have pulseaudio-dlna installed.  I am going to uninstall it and see if that solves it.  Maybe they, or their dependencies, conflict.

**Comment by xmbwd** [comment]
Problem solved by uninstalling pulseaudio-dlna.  No idea why they conflict.  But mkchromecast now works.  That said, pulseaudio-dlna discovers other devices that mkchromecast does not (e.g., for me, my Denon AVR that has dlna & Airplay capability).  So it would be great if they could be made to play nice....

**Comment by xmbwd** [comment]
Another issue that I wanted to relay:  although removing `pulseaudio-dlna` did something that allowed `mkchromecast` to work, I can only cast from my computer to the Chromecast if it is connected via wifi.  If the computer is connected either (A) via ethernet (to the same network) or (B) via both ethernet and wifi to the same network, `mkchromecast` can't find the device.

Is that weird?  [Google says](https://productforums.google.com/forum/#!topic/chromecast/Xqmubkscrgo) once the Chromecast is set up via a wifi-connected device, you should be able to cast via an ethernet-connected device.

**Comment by muammar** [comment]
@xmbwd I have both installed. Indeed, I am the debian maintainer of [pulseaudio-dlna](https://packages.debian.org/unstable/pulseaudio-dlna). I cannot reproduce this error. I tried the following:

* Started streaming using `mkchromecast`. Everything worked as usual.
* Started using `pulseaudio-dlna`, and it was capable of finding my CCA. After selecting the pulseaudio sink, I was able to stream with `pulseaudio-dlna`. `mkchromecast`  kept the local server up, but `pulseaudio-dlna` was casting the audio.

**Comment by xmbwd** [comment]
@muammar thanks for testing that.  I resolved the general issue by replacing a router that was between my primary router and my computer doing the casting.  That was likely the primary source of the wifi v. ethernet issue.

I don't know why `pulseaudio-dlna` and `mkchromecast` didn't work when on the same computer.  Or why removing `pulseaudio-dlna` allowed `mkchromecast` to work.  But I think the most likely answer is the router issue previously mentioned.  It did something to mess with `pulseaudio-dlna` that did not have any effect on casting via the Google Chrome casting plugin.  

Both `pulseaudio-dlna` and `mkchromecast` are great.  Unfortunately, I just can't seem to rid them of the sound delay to my ChromeCast Audio -- which increases over each casting session from about 2 seconds to over 30 -- or the distortion when using the volume up or down buttons.  I tried all combinations of renderers and encoders, to no avail.

**Comment by muammar** [comment]
> 
> @muammar thanks for testing that. I resolved the general issue by replacing a router that was between my primary router and my computer doing the casting. That was likely the primary source of the wifi v. ethernet issue.
> 

You are welcome. Nice to know you were able to found the problem with the network.

> I don't know why pulseaudio-dlna and mkchromecast didn't work when on the same computer. Or why removing pulseaudio-dlna allowed mkchromecast to work. But I think the most likely answer is the router issue previously mentioned. It did something to mess with pulseaudio-dlna that did not have any effect on casting via the Google Chrome casting plugin.
> 
> Both pulseaudio-dlna and mkchromecast are great. Unfortunately, I just can't seem to rid them of the sound delay to my ChromeCast Audio -- which increases over each casting session from about 2 seconds to over 30 -- or the distortion when using the volume up or down buttons. I tried all combinations of renderers and encoders, to no avail.

Regarding sound delay, I remember that it improved when I changed to a better router. Some months ago I changed ISP, and the new wifi router that I was given was better and the problem with delay was solved. This is mostly a network problem I am afraid. 

The problem with the volume I also experiment it some times in Linux. It does not happen in macOS, and it is more likely to be related to pulseaudio. That's why it is better to set full volume in `pavucontrol`, and control the volume of the google cast device either by using the **mkchromecast**'s GUI volume slider or pressing the <kbd>u</kbd> and <kbd>d</kbd> when passing the `--volume` flag in the console. Thanks for all your feedback!. 

PS. I fixed the problem you reported about closing the preferences pane.

**Comment by muammar** [comment]
I am closing this report, but feel free to reopen it if you think it is necessary. I have linked [this information in the wiki](https://github.com/muammar/mkchromecast/wiki/FAQ#no-cast-devices-found) so that others can benefit from it. Thanks.

**Comment by xmbwd** [comment]
I don't want to reopen this.  Just a comment that the sound delay issue does not occur on the same network using either an Android phone or a Mac.  So I don't think it is my router, or if it is, the issue it is having does not occur with other platforms.  

Thanks again for all of your help and this great tool.

**Comment by vivi90** [comment]
Hello.
For me it still not found the device with mkchromecast v0.3.8.1.
Then i have installed pulseaudio-dlna. And this works great with flac and aac but not with mp3 or wav.
But mkchromecast still don't work at all. :-(

**Comment by vivi90** [comment]
Command line output:
----------------------------
vivien@vivien-nb:~$ mkchromecast --encoder-backend ffmpeg --codec aac --host 192.168.178.42
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: ffmpeg
Selected audio codec: aac
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 11547
PID of streaming process: 11613
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
No devices found!
Cleaning up /tmp/...
[Done]
Getötet

**Comment by vivi90** [comment]
My device is a Sony UBP-X800.

**Comment by muammar** [comment]
>
> My device is a Sony UBP-X800.
>

Does it have a chromecast built-in? if not, then this application
won't work. Mkchromecast can cast to chromecast, chromecast audio, and
sonos.

**Comment by MReed1959** [comment]
Mine stopped working when I installed python-pip, and then let it do an upgrade. When I then removed python-pip it started working again - didn't even need a reboot.

**Comment by alazyworkaholic** [comment]
Ubuntu 18.04 i386. I installed mkchromecast. Didn't find any devices. Installed pulseaudio-dlna. Tried to search for devices / create config with pulseaudio-dlna, found nothing. Tried again with mkchromecast, found nothing. Removed pulseaudio-dlna, searched for devices with mkchromecast, found my device!

**Comment by elisaado** [comment]
`pulseaudio-dlna` can find it here, but `mkchromecast` can't, WHAT.

**Comment by MReed1959** [comment]
mkchromecast simply uses network commands to access the Chromecast.

Try some of these commands yourself, after you figure out the Chromecast Address

https://forum.xda-developers.com/android-tv/chromecast/chromecast-unofficial-api-information-t2788502

**Comment by muammar** [comment]
@elisaado version of pychromecast you are using?

**Comment by elisaado** [comment]
Hi @muammar, it seems that `pychromecast` is not installed, as `pip show pychromecast` (I tried both pip2 and pip3) exit with code 1

**Comment by Hubro** [comment]
I had this issue when installing mkchromecast on Manjaro from AUR. The installer didn't install pychromecast, so running `mkchromecast -d` would instantly respond with "No devices found!".

Installing pychromecast manually fixed this problem:

    $ sudo pip install pychromecast

**Comment by elisaado** [comment]
Wow, that works! Thank you @Hubro.

**Comment by tsbarnes** [comment]
I'm running into this issue on Manjaro, with pychromecast installed. If I open up the Python console and make pychromecast discover devices it finds them just fine, but mkchromecast always says no devices found.

**Comment by GameKyuubi** [comment]
> I had this issue when installing mkchromecast on Manjaro from AUR. The installer didn't install pychromecast, so running `mkchromecast -d` would instantly respond with "No devices found!".
> 
> Installing pychromecast manually fixed this problem:
> 
> ```
> $ sudo pip install pychromecast
> ```

I'd just like to say that this got it working on Arch for me.  Is it weird that this is still an issue?
